before_install:
    - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
    - travis_retry sudo add-apt-repository -y ppa:glondu/ppa
    - travis_retry sudo apt-get update
    - travis_retry sudo apt-get install coq-8.4 ghc
script:
    - make
    - cd extraction
    - make clean
    - make test
    - cd ../Haskell
    - ghc -fno-code *.hs
